In [1]:
set.seed(123) #랜덤 시드를 고정하면 같은 값으로 처리됨
# 0.0~1.0 미만의 난수 발생
runif(1) #난수 1개
runif(10) #난수 10개

[1] 0.2875775

 [1] 0.7883051 0.4089769 0.8830174 0.9404673 0.0455565 0.5281055 0.8924190
 [8] 0.5514350 0.4566147 0.9568333

In [2]:
#동전 던지기
coin<-function(){
    x<-runif(1) #난수 발생
    print(x)
    if(x<=0.5) result<-0 #0.5이하이면 0, 아니면 1
    else result <-1
    return(result)
}
coin()

[1] 0.4533342

[1] 0

In [10]:
#가위 바위 보
rock <- function() {
    x<- runif(1) #난수 발생
    if (x<=1/3) result <-1
    else if(x<=2/3) result<-2
    else result<-3
        return(result)
}
for(i in 1:10){
    print(rock())
}

[1] 2
[1] 3
[1] 3
[1] 1
[1] 3
[1] 3
[1] 2
[1] 3
[1] 3
[1] 1

In [11]:
#동전 던지기
coin<-function(){
    x<-runif(1) #난수 발생
    #print(x)
    if(x<=0.5) result<-0 #0.5이하이면 0, 아니면 1
    else result <-1
    return(result)
}
coin()

[1] 1

In [12]:
#동전던지기 (앞면이 나오는 경우의 합계)
mycointoss <- function(n) {
    count <-0
    for (i in 1:n) {
        x<-coin()
        if (x==0) count<- count+1
    }
    return(count)
}
mycointoss(10)
mycointoss(100)
mycointoss(1000)
mycointoss(10000)

[1] 4

[1] 58

[1] 498

[1] 5093

In [25]:
seq(1,100,by=1)

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [20]:
mymonte(10)

[1] 0.7

In [15]:
mymonte <- function(n) {
    count <-0
    for ( i in 1:n) {
        count <- count + coin()
    }
    return(count/n)
}
# mymonte(10)
# mymonte(100)
# mymonte(1000)
# mymonte(10000)
# mymonte(100000)
for (i in seq(1,100000,by=10000)){
    print(mymonte(i))
}

[1] 1
[1] 0.4992501
[1] 0.5020249
[1] 0.50125
[1] 0.4983125
[1] 0.50141
[1] 0.5010083
[1] 0.4975215
[1] 0.4987313
[1] 0.4986722

In [17]:
mymonte2<-function(n,k,func){ #실험횟수, 10회, mymonte 함수 호출
    count <-0
    for (i in 1:n) {
        count <- count + func(k)
    }
    return(count/n)
}
#1~100,step1
for (i in seq(1,100,by=1)){
    print(mymonte2(i,10,mymonte))

}

[1] 0.6
[1] 0.45
[1] 0.5333333
[1] 0.45
[1] 0.46
[1] 0.6
[1] 0.4285714
[1] 0.575
[1] 0.5
[1] 0.55
[1] 0.5272727
[1] 0.5333333
[1] 0.5076923
[1] 0.4714286
[1] 0.4533333
[1] 0.54375
[1] 0.4823529
[1] 0.4777778
[1] 0.4684211
[1] 0.525
[1] 0.552381
[1] 0.4772727
[1] 0.5043478
[1] 0.5083333
[1] 0.528
[1] 0.5076923
[1] 0.4666667
[1] 0.4928571
[1] 0.5586207
[1] 0.5466667
[1] 0.5258065
[1] 0.48125
[1] 0.4242424
[1] 0.5176471
[1] 0.4914286
[1] 0.5
[1] 0.5432432
[1] 0.4921053
[1] 0.5179487
[1] 0.5075
[1] 0.4829268
[1] 0.5190476
[1] 0.5162791
[1] 0.4636364
[1] 0.5111111
[1] 0.4978261
[1] 0.5042553
[1] 0.5354167
[1] 0.5204082
[1] 0.484
[1] 0.5235294
[1] 0.5346154
[1] 0.5056604
[1] 0.5314815
[1] 0.46
[1] 0.5232143
[1] 0.4982456
[1] 0.4931034
[1] 0.479661
[1] 0.5616667
[1] 0.4852459
[1] 0.5193548
[1] 0.531746
[1] 0.48125
[1] 0.5092308
[1] 0.45
[1] 0.5208955
[1] 0.5191176
[1] 0.5086957
[1] 0.51
[1] 0.4971831
[1] 0.4625
[1] 0.509589
[1] 0.4662162
[1] 0.5266667
[1] 0.5381579
[1] 0.5142857
[1] 0.4858974
[1] 0.4734177
[1] 0.47125
[1] 0.4777778
[1] 0.5012195
[1] 0.5048193
[1] 0.5261905
[1] 0.4964706
[1] 0.4895349
[1] 0.4873563
[1] 0.5147727
[1] 0.505618
[1] 0.4811111
[1] 0.510989
[1] 0.4978261
[1] 0.5043011
[1] 0.5042553
[1] 0.5252632
[1] 0.4833333
[1] 0.5113402
[1] 0.5010204
[1] 0.4757576
[1] 0.481

In [28]:
a<-runif(1)
a
a*6
trunc(a*6) #버림
trunc(a*6)+1

[1] 0.693619

[1] 4.161714

[1] 4

[1] 5

In [30]:
#주사위 던지기
dice <- function(n){
    count1<-0
    count2<-0
    count3<-0
    count4<-0
    count5<-0
    count6<-0
    cat("n=",n,"\n")
    for(i in 1:n){
        x<-(trunc(runif(1)*6)+1) #난수에 6을 곱하고 버림 +1
        if(x==1) count1=count1+1
        if(x==2) count2=count2+1
        if(x==3) count3=count3+1
        if(x==4) count4=count4+1
        if(x==5) count5=count5+1
        if(x==6) count6=count6+1
    }
    cat("1 number occurs :",count1,"\n")
    cat("2 number occurs :",count2,"\n")
    cat("3 number occurs :",count3,"\n")
    cat("4 number occurs :",count4,"\n")
    cat("5 number occurs :",count5,"\n")
    cat("6 number occurs :",count6,"\n")
}
for (i in seq(10,2000,by=10)){ #10~2000, 10씩 증가
    dice(i)
}

n= 10
1 number occurs : 3
2 number occurs : 2
3 number occurs : 1
4 number occurs : 1
5 number occurs : 2
6 number occurs : 1
n= 20
1 number occurs : 3
2 number occurs : 7
3 number occurs : 2
4 number occurs : 1
5 number occurs : 3
6 number occurs : 4
n= 30
1 number occurs : 9
2 number occurs : 5
3 number occurs : 6
4 number occurs : 3
5 number occurs : 3
6 number occurs : 4
n= 40
1 number occurs : 3
2 number occurs : 13
3 number occurs : 6
4 number occurs : 6
5 number occurs : 6
6 number occurs : 6
n= 50
1 number occurs : 9
2 number occurs : 4
3 number occurs : 10
4 number occurs : 8
5 number occurs : 8
6 number occurs : 11
n= 60
1 number occurs : 12
2 number occurs : 9
3 number occurs : 10
4 number occurs : 11
5 number occurs : 10
6 number occurs : 8
n= 70
1 number occurs : 7
2 number occurs : 12
3 number occurs : 13
4 number occurs : 15
5 number occurs : 12
6 number occurs : 11
n= 80
1 number occurs : 9
2 number occurs : 14
3 number occurs : 11
4 number occurs : 16
5 number occurs : 18
6 number occurs : 12
n= 90
1 number occurs : 20
2 number occurs : 13
3 number occurs : 22
4 number occurs : 13
5 number occurs : 8
6 number occurs : 14
n= 100
1 number occurs : 12
2 number occurs : 15
3 number occurs : 18
4 number occurs : 19
5 number occurs : 22
6 number occurs : 14
n= 110
1 number occurs : 18
2 number occurs : 21
3 number occurs : 21
4 number occurs : 11
5 number occurs : 16
6 number occurs : 23
n= 120
1 number occurs : 12
2 number occurs : 20
3 number occurs : 20
4 number occurs : 26
5 number occurs : 22
6 number occurs : 20
n= 130
1 number occurs : 22
2 number occurs : 28
3 number occurs : 15
4 number occurs : 27
5 number occurs : 18
6 number occurs : 20
n= 140
1 number occurs : 16
2 number occurs : 29
3 number occurs : 15
4 number occurs : 30
5 number occurs : 19
6 number occurs : 31
n= 150
1 number occurs : 28
2 number occurs : 24
3 number occurs : 17
4 number occurs : 21
5 number occurs : 28
6 number occurs : 32
n= 160
1 number occurs : 21
2 number occurs : 33
3 number occurs : 24
4 number occurs : 33
5 number occurs : 23
6 number occurs : 26
n= 170
1 number occurs : 27
2 number occurs : 42
3 number occurs : 23
4 number occurs : 26
5 number occurs : 21
6 number occurs : 31
n= 180
1 number occurs : 19
2 number occurs : 37
3 number occurs : 32
4 number occurs : 32
5 number occurs : 27
6 number occurs : 33
n= 190
1 number occurs : 43
2 number occurs : 21
3 number occurs : 37
4 number occurs : 38
5 number occurs : 25
6 number occurs : 26
n= 200
1 number occurs : 41
2 number occurs : 30
3 number occurs : 29
4 number occurs : 30
5 number occurs : 40
6 number occurs : 30
n= 210
1 number occurs : 33
2 number occurs : 26
3 number occurs : 31
4 number occurs : 42
5 number occurs : 37
6 number occurs : 41
n= 220
1 number occurs : 41
2 number occurs : 37
3 number occurs : 39
4 number occurs : 29
5 number occurs : 45
6 number occurs : 29
n= 230
1 number occurs : 33
2 number occurs : 35
3 number occurs : 40
4 number occurs : 34
5 number occurs : 41
6 number occurs : 47
n= 240
1 number occurs : 53
2 number occurs : 41
3 number occurs : 25
4 number occurs : 42
5 number occurs : 47
6 number occurs : 32
n= 250
1 number occurs : 53
2 number occurs : 33
3 number occurs : 43
4 number occurs : 36
5 number occurs : 44
6 number occurs : 41
n= 260
1 number occurs : 36
2 number occurs : 38
3 number occurs : 52
4 number occurs : 41
5 number occurs : 40
6 number occurs : 53
n= 270
1 number occurs : 42
2 number occurs : 48
3 number occurs : 40
4 number occurs : 52
5 number occurs : 46
6 number occurs : 42
n= 280
1 number occurs : 38
2 number occurs : 50
3 number occurs : 45
4 number occurs : 48
5 number occurs : 51
6 number occurs : 48
n= 290
1 number occurs : 56
2 number occurs : 48
3 number occurs : 50
4 number occurs : 50
5 number occurs : 43
6 number occurs : 43
n= 300
1 number occurs : 59
2 number occurs : 47
3 number occurs : 49
4 number occurs : 55
5 number occurs : 44
6 number occurs : 46
n= 310
1 number occurs : 51
2 number occurs : 60
3 number occurs : 48
4 number occurs : 52
5 number occurs : 53
6 number occurs : 46
n= 320
1 number occurs : 63
2 number occurs : 46
3 number occurs : 62
4 number occurs : 58
5 number occurs : 38
6 number occurs : 53
n= 330
1 number occurs : 51
2 number occurs : 52
3 number occurs : 51
4 number occurs : 55
5 number occurs : 68
6 number occurs : 53
n= 340
1 number occurs : 56
2 number occurs : 52
3 number occurs : 56
4 number occurs : 61
5 number occurs : 48
6 number occurs : 67
n= 350
1 number occurs : 63
2 number occurs : 53
3 number occurs : 54
4 number occurs : 62
5 number occurs : 60
6 number occurs : 58
n= 360
1 number occurs : 62
2 number occurs : 61
3 number occurs : 52
4 number occurs : 51
5 number occurs : 69
6 number occurs : 65
n= 370
1 number occurs : 59
2 number occurs : 63
3 number occurs : 71
4 number occurs : 56
5 number occurs : 63
6 number occurs : 58
n= 380
1 number occurs : 59
2 number occurs : 65
3 number occurs : 66
4 number occurs : 58
5 number occurs : 64
6 number occurs : 68
n= 390
1 number occurs : 64
2 number occurs : 58
3 number occurs : 75
4 number occurs : 76
5 number occurs : 60
6 number occurs : 57
n= 400
1 number occurs : 71
2 number occurs : 62
3 number occurs : 69
4 number occurs : 68
5 number occurs : 65
6 number occurs : 65
n= 410
1 number occurs : 58
2 number occurs : 77
3 number occurs : 61
4 number occurs : 76
5 number occurs : 81
6 number occurs : 57
n= 420
1 number occurs : 65
2 number occurs : 73
3 number occurs : 68
4 number occurs : 79
5 number occurs : 61
6 number occurs : 74
n= 430
1 number occurs : 72
2 number occurs : 74
3 number occurs : 68
4 number occurs : 70
5 number occurs : 63
6 number occurs : 83
n= 440
1 number occurs : 91
2 number occurs : 68
3 number occurs : 76
4 number occurs : 69
5 number occurs : 78
6 number occurs : 58
n= 450
1 number occurs : 64
2 number occurs : 81
3 number occurs : 56
4 number occurs : 85
5 number occurs : 89
6 number occurs : 75
n= 460
1 number occurs : 79
2 number occurs : 70
3 number occurs : 80
4 number occurs : 78
5 number occurs : 78
6 number occurs : 75
n= 470
1 number occurs : 61
2 number occurs : 81
3 number occurs : 85
4 number occurs : 89
5 number occurs : 66
6 number occurs : 88
n= 480
1 number occurs : 71
2 number occurs : 66
3 number occurs : 75
4 number occurs : 101
5 number occurs : 93
6 number occurs : 74
n= 490
1 number occurs : 82
2 number occurs : 79
3 number occurs : 85
4 number occurs : 83
5 number occurs : 80
6 number occurs : 81
n= 500
1 number occurs : 93
2 number occurs : 85
3 number occurs : 77
4 number occurs : 72
5 number occurs : 89
6 number occurs : 84
n= 510
1 number occurs : 91
2 number occurs : 80
3 number occurs : 73
4 number occurs : 98
5 number occurs : 94
6 number occurs : 74
n= 520
1 number occurs : 88
2 number occurs : 87
3 number occurs : 96
4 number occurs : 73
5 number occurs : 84
6 number occurs : 92
n= 530
1 number occurs : 86
2 number occurs : 92
3 number occurs : 82
4 number occurs : 91
5 number occurs : 90
6 number occurs : 89
n= 540
1 number occurs : 85
2 number occurs : 92
3 number occurs : 91
4 number occurs : 92
5 number occurs : 85
6 number occurs : 95
n= 550
1 number occurs : 89
2 number occurs : 94
3 number occurs : 90
4 number occurs : 101
5 number occurs : 78
6 number occurs : 98
n= 560
1 number occurs : 82
2 number occurs : 96
3 number occurs : 89
4 number occurs : 99
5 number occurs : 97
6 number occurs : 97
n= 570
1 number occurs : 97
2 number occurs : 102
3 number occurs : 99
4 number occurs : 85
5 number occurs : 91
6 number occurs : 96
n= 580
1 number occurs : 104
2 number occurs : 92
3 number occurs : 96
4 number occurs : 90
5 number occurs : 101
6 number occurs : 97
n= 590
1 number occurs : 71
2 number occurs : 99
3 number occurs : 89
4 number occurs : 122
5 number occurs : 104
6 number occurs : 105
n= 600
1 number occurs : 102
2 number occurs : 99
3 number occurs : 99
4 number occurs : 93
5 number occurs : 104
6 number occurs : 103
n= 610
1 number occurs : 87
2 number occurs : 121
3 number occurs : 94
4 number occurs : 101
5 number occurs : 104
6 number occurs : 103
n= 620
1 number occurs : 94
2 number occurs : 118
3 number occurs : 101
4 number occurs : 91
5 number occurs : 124
6 number occurs : 92
n= 630
1 number occurs : 95
2 number occurs : 108
3 number occurs : 108
4 number occurs : 104
5 number occurs : 111
6 number occurs : 104
n= 640
1 number occurs : 123
2 number occurs : 98
3 number occurs : 116
4 number occurs : 100
5 number occurs : 106
6 number occurs : 97
n= 650
1 number occurs : 102
2 number occurs : 110
3 number occurs : 110
4 number occurs : 107
5 number occurs : 118
6 number occurs : 103
n= 660
1 number occurs : 105
2 number occurs : 117
3 number occurs : 129
4 number occurs : 105
5 number occurs : 112
6 number occurs : 92
n= 670
1 number occurs : 107
2 number occurs : 127
3 number occurs : 117
4 number occurs : 98
5 number occurs : 100
6 number occurs : 121
n= 680
1 number occurs : 109
2 number occurs : 138
3 number occurs : 112
4 number occurs : 121
5 number occurs : 98
6 number occurs : 102
n= 690
1 number occurs : 105
2 number occurs : 125
3 number occurs : 111
4 number occurs : 113
5 number occurs : 116
6 number occurs : 120
n= 700
1 number occurs : 114
2 number occurs : 116
3 number occurs : 124
4 number occurs : 111
5 number occurs : 116
6 number occurs : 119
n= 710
1 number occurs : 122
2 number occurs : 119
3 number occurs : 110
4 number occurs : 109
5 number occurs : 113
6 number occurs : 137
n= 720
1 number occurs : 115
2 number occurs : 118
3 number occurs : 107
4 number occurs : 131
5 number occurs : 124
6 number occurs : 125
n= 730
1 number occurs : 133
2 number occurs : 103
3 number occurs : 120
4 number occurs : 120
5 number occurs : 130
6 number occurs : 124
n= 740
1 number occurs : 134
2 number occurs : 129
3 number occurs : 124
4 number occurs : 132
5 number occurs : 108
6 number occurs : 113
n= 750
1 number occurs : 120
2 number occurs : 120
3 number occurs : 126
4 number occurs : 133
5 number occurs : 106
6 number occurs : 145
n= 760
1 number occurs : 142
2 number occurs : 121
3 number occurs : 134
4 number occurs : 115
5 number occurs : 130
6 number occurs : 118
n= 770
1 number occurs : 129
2 number occurs : 127
3 number occurs : 121
4 number occurs : 148
5 number occurs : 132
6 number occurs : 113
n= 780
1 number occurs : 140
2 number occurs : 114
3 number occurs : 130
4 number occurs : 125
5 number occurs : 119
6 number occurs : 152
n= 790
1 number occurs : 131
2 number occurs : 139
3 number occurs : 116
4 number occurs : 123
5 number occurs : 147
6 number occurs : 134
n= 800
1 number occurs : 141
2 number occurs : 122
3 number occurs : 126
4 number occurs : 136
5 number occurs : 135
6 number occurs : 140
n= 810
1 number occurs : 129
2 number occurs : 145
3 number occurs : 137
4 number occurs : 134
5 number occurs : 146
6 number occurs : 119
n= 820
1 number occurs : 120
2 number occurs : 142
3 number occurs : 122
4 number occurs : 163
5 number occurs : 152
6 number occurs : 121
n= 830
1 number occurs : 119
2 number occurs : 159
3 number occurs : 153
4 number occurs : 114
5 number occurs : 144
6 number occurs : 141
n= 840
1 number occurs : 132
2 number occurs : 158
3 number occurs : 144
4 number occurs : 140
5 number occurs : 130
6 number occurs : 136
n= 850
1 number occurs : 139
2 number occurs : 138
3 number occurs : 146
4 number occurs : 144
5 number occurs : 146
6 number occurs : 137
n= 860
1 number occurs : 154
2 number occurs : 144
3 number occurs : 160
4 number occurs : 147
5 number occurs : 129
6 number occurs : 126
n= 870
1 number occurs : 151
2 number occurs : 159
3 number occurs : 129
4 number occurs : 137
5 number occurs : 137
6 number occurs : 157
n= 880
1 number occurs : 154
2 number occurs : 163
3 number occurs : 143
4 number occurs : 137
5 number occurs : 121
6 number occurs : 162
n= 890
1 number occurs : 141
2 number occurs : 141
3 number occurs : 160
4 number occurs : 145
5 number occurs : 154
6 number occurs : 149
n= 900
1 number occurs : 158
2 number occurs : 139
3 number occurs : 160
4 number occurs : 157
5 number occurs : 149
6 number occurs : 137
n= 910
1 number occurs : 152
2 number occurs : 152
3 number occurs : 141
4 number occurs : 146
5 number occurs : 167
6 number occurs : 152
n= 920
1 number occurs : 169
2 number occurs : 133
3 number occurs : 149
4 number occurs : 164
5 number occurs : 145
6 number occurs : 160
n= 930
1 number occurs : 160
2 number occurs : 154
3 number occurs : 174
4 number occurs : 160
5 number occurs : 162
6 number occurs : 120
n= 940
1 number occurs : 154
2 number occurs : 147
3 number occurs : 162
4 number occurs : 152
5 number occurs : 171
6 number occurs : 154
n= 950
1 number occurs : 147
2 number occurs : 174
3 number occurs : 139
4 number occurs : 157
5 number occurs : 157
6 number occurs : 176
n= 960
1 number occurs : 142
2 number occurs : 166
3 number occurs : 150
4 number occurs : 167
5 number occurs : 147
6 number occurs : 188
n= 970
1 number occurs : 178
2 number occurs : 163
3 number occurs : 147
4 number occurs : 172
5 number occurs : 151
6 number occurs : 159
n= 980
1 number occurs : 151
2 number occurs : 164
3 number occurs : 173
4 number occurs : 165
5 number occurs : 153
6 number occurs : 174
n= 990
1 number occurs : 155
2 number occurs : 152
3 number occurs : 175
4 number occurs : 168
5 number occurs : 175
6 number occurs : 165
n= 1000
1 number occurs : 178
2 number occurs : 159
3 number occurs : 160
4 number occurs : 168
5 number occurs : 165
6 number occurs : 170
n= 1010
1 number occurs : 162
2 number occurs : 158
3 number occurs : 173
4 number occurs : 181
5 number occurs : 168
6 number occurs : 168
n= 1020
1 number occurs : 167
2 number occurs : 175
3 number occurs : 183
4 number occurs : 173
5 number occurs : 169
6 number occurs : 153
n= 1030
1 number occurs : 163
2 number occurs : 168
3 number occurs : 181
4 number occurs : 194
5 number occurs : 161
6 number occurs : 163
n= 1040
1 number occurs : 175
2 number occurs : 182
3 number occurs : 164
4 number occurs : 175
5 number occurs : 169
6 number occurs : 175
n= 1050
1 number occurs : 190
2 number occurs : 148
3 number occurs : 186
4 number occurs : 173
5 number occurs : 184
6 number occurs : 169
n= 1060
1 number occurs : 192
2 number occurs : 168
3 number occurs : 172
4 number occurs : 168
5 number occurs : 175
6 number occurs : 185
n= 1070
1 number occurs : 201
2 number occurs : 158
3 number occurs : 164
4 number occurs : 184
5 number occurs : 189
6 number occurs : 174
n= 1080
1 number occurs : 195
2 number occurs : 191
3 number occurs : 185
4 number occurs : 162
5 number occurs : 181
6 number occurs : 166
n= 1090
1 number occurs : 220
2 number occurs : 177
3 number occurs : 186
4 number occurs : 171
5 number occurs : 150
6 number occurs : 186
n= 1100
1 number occurs : 175
2 number occurs : 193
3 number occurs : 177
4 number occurs : 199
5 number occurs : 181
6 number occurs : 175
n= 1110
1 number occurs : 167
2 number occurs : 203
3 number occurs : 182
4 number occurs : 198
5 number occurs : 181
6 number occurs : 179
n= 1120
1 number occurs : 185
2 number occurs : 179
3 number occurs : 199
4 number occurs : 198
5 number occurs : 186
6 number occurs : 173
n= 1130
1 number occurs : 175
2 number occurs : 182
3 number occurs : 191
4 number occurs : 184
5 number occurs : 189
6 number occurs : 209
n= 1140
1 number occurs : 195
2 number occurs : 161
3 number occurs : 222
4 number occurs : 186
5 number occurs : 177
6 number occurs : 199
n= 1150
1 number occurs : 197
2 number occurs : 180
3 number occurs : 201
4 number occurs : 188
5 number occurs : 181
6 number occurs : 203
n= 1160
1 number occurs : 186
2 number occurs : 182
3 number occurs : 190
4 number occurs : 192
5 number occurs : 225
6 number occurs : 185
n= 1170
1 number occurs : 204
2 number occurs : 195
3 number occurs : 180
4 number occurs : 207
5 number occurs : 196
6 number occurs : 188
n= 1180
1 number occurs : 179
2 number occurs : 198
3 number occurs : 207
4 number occurs : 221
5 number occurs : 169
6 number occurs : 206
n= 1190
1 number occurs : 206
2 number occurs : 210
3 number occurs : 211
4 number occurs : 191
5 number occurs : 176
6 number occurs : 196
n= 1200
1 number occurs : 202
2 number occurs : 189
3 number occurs : 201
4 number occurs : 181
5 number occurs : 222
6 number occurs : 205
n= 1210
1 number occurs : 203
2 number occurs : 191
3 number occurs : 210
4 number occurs : 214
5 number occurs : 195
6 number occurs : 197
n= 1220
1 number occurs : 201
2 number occurs : 213
3 number occurs : 212
4 number occurs : 221
5 number occurs : 186
6 number occurs : 187
n= 1230
1 number occurs : 210
2 number occurs : 204
3 number occurs : 216
4 number occurs : 221
5 number occurs : 201
6 number occurs : 178
n= 1240
1 number occurs : 199
2 number occurs : 200
3 number occurs : 199
4 number occurs : 198
5 number occurs : 215
6 number occurs : 229
n= 1250
1 number occurs : 212
2 number occurs : 206
3 number occurs : 215
4 number occurs : 230
5 number occurs : 195
6 number occurs : 192
n= 1260
1 number occurs : 209
2 number occurs : 227
3 number occurs : 214
4 number occurs : 192
5 number occurs : 194
6 number occurs : 224
n= 1270
1 number occurs : 218
2 number occurs : 207
3 number occurs : 237
4 number occurs : 217
5 number occurs : 208
6 number occurs : 183
n= 1280
1 number occurs : 214
2 number occurs : 218
3 number occurs : 220
4 number occurs : 196
5 number occurs : 217
6 number occurs : 215
n= 1290
1 number occurs : 223
2 number occurs : 243
3 number occurs : 207
4 number occurs : 211
5 number occurs : 215
6 number occurs : 191
n= 1300
1 number occurs : 227
2 number occurs : 226
3 number occurs : 200
4 number occurs : 207
5 number occurs : 200
6 number occurs : 240
n= 1310
1 number occurs : 228
2 number occurs : 197
3 number occurs : 213
4 number occurs : 252
5 number occurs : 214
6 number occurs : 206
n= 1320
1 number occurs : 238
2 number occurs : 202
3 number occurs : 209
4 number occurs : 232
5 number occurs : 209
6 number occurs : 230
n= 1330
1 number occurs : 214
2 number occurs : 211
3 number occurs : 229
4 number occurs : 247
5 number occurs : 218
6 number occurs : 211
n= 1340
1 number occurs : 212
2 number occurs : 239
3 number occurs : 217
4 number occurs : 213
5 number occurs : 211
6 number occurs : 248
n= 1350
1 number occurs : 260
2 number occurs : 221
3 number occurs : 206
4 number occurs : 237
5 number occurs : 197
6 number occurs : 229
n= 1360
1 number occurs : 238
2 number occurs : 229
3 number occurs : 225
4 number occurs : 210
5 number occurs : 219
6 number occurs : 239
n= 1370
1 number occurs : 224
2 number occurs : 223
3 number occurs : 230
4 number occurs : 241
5 number occurs : 236
6 number occurs : 216
n= 1380
1 number occurs : 222
2 number occurs : 235
3 number occurs : 219
4 number occurs : 225
5 number occurs : 229
6 number occurs : 250
n= 1390
1 number occurs : 235
2 number occurs : 210
3 number occurs : 259
4 number occurs : 254
5 number occurs : 221
6 number occurs : 211
n= 1400
1 number occurs : 231
2 number occurs : 227
3 number occurs : 261
4 number occurs : 245
5 number occurs : 226
6 number occurs : 210
n= 1410
1 number occurs : 233
2 number occurs : 232
3 number occurs : 252
4 number occurs : 215
5 number occurs : 250
6 number occurs : 228
n= 1420
1 number occurs : 227
2 number occurs : 235
3 number occurs : 234
4 number occurs : 254
5 number occurs : 245
6 number occurs : 225
n= 1430
1 number occurs : 236
2 number occurs : 248
3 number occurs : 251
4 number occurs : 229
5 number occurs : 222
6 number occurs : 244
n= 1440
1 number occurs : 218
2 number occurs : 246
3 number occurs : 240
4 number occurs : 234
5 number occurs : 264
6 number occurs : 238
n= 1450
1 number occurs : 237
2 number occurs : 252
3 number occurs : 254
4 number occurs : 241
5 number occurs : 238
6 number occurs : 228
n= 1460
1 number occurs : 239
2 number occurs : 253
3 number occurs : 254
4 number occurs : 233
5 number occurs : 250
6 number occurs : 231
n= 1470
1 number occurs : 237
2 number occurs : 228