In [1]:
names(iris) #변수명
attributes(iris) #변수명, 자료형, 행의 인덱스
str(iris) #데이터 구조

[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

$names
[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

$class
[1] "data.frame"

$row.names
  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...

In [16]:
set.seed(123)
nrow(iris) #행의 수
ncol(iris) #필드 수
a<-sample(1:150, 150*0.8)
a
length(a)

[1] 150

[1] 5

  [1]  14  50 118  43 150 148  90  91 143  92 137  99  72  26   7  78  81 147
 [19] 103 117  76  32 106 109 136   9  41  74  23  27  60  53 126 119 121  96
 [37]  38  89  34  93  69 138 130  63  13  82  97 142  25 114  21  79 124  47
 [55] 144 120  16   6 127  86 132  39  31 134 149 112   4 128 110 102  52  22
 [73] 129  87  35  40  30  12  88 123  64 146  67 122  37   8  51  10 115  42
 [91]  44  85 107 139  73  20  46  17  54 108  75  80  71  15  24  68 133 145
[109]  29 104  45 140 101 135  95 116   5 111  94  49

[1] 120

In [9]:
set.seed(123) #랜덤 시드 고정
dim(iris) #데이터의 차원
#nrow() 행의 수
#sample (A,B) A에서 B를 샘플링
idx<-sample(1:nrow(iris), nrow(iris)*0.8)
tr<-iris[idx,] #학습용
te<-iris[-idx] #검증용
dim(tr)
dim(te)
head(tr)
head(te)

[1] 150   5

[1] 120   5

[1] 150   3

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
14  4.3          3.0         1.1          0.1         setosa
50  5.0          3.3         1.4          0.2         setosa
118 7.7          3.8         6.7          2.2         virginica
43  4.4          3.2         1.3          0.2         setosa
150 5.9          3.0         5.1          1.8         virginica
148 6.5          3.0         5.2          2.0         virginica

  Sepal.Length Sepal.Width Petal.Length
1 5.1          3.5         1.4
2 4.9          3.0         1.4
3 4.7          3.2         1.3
4 4.6          3.1         1.5
5 5.0          3.6         1.4
6 5.4          3.9         1.7

In [17]:
name<-c('김철수','이미영','홍상수','이찬수','송희연','최승희',
       '박만수','민지영','정선호','한상후')
score<-c(90,85,70,85,60,66,77,88,99,100)
df<-data.frame(Name=name,Score=score)
df

   Name   Score
1  김철수  90
2  이미영  85
3  홍상수  70
4  이찬수  85
5  송희연  60
6  최승희  66
7  박만수  77
8  민지영  88
9  정선호  99
10 한상후 100

In [18]:
#install.packages('cvTools')

Installing package into 'C:/Users/tjoeun302-18/Documents/R/win-library/3.6'
(as 'lib' is unspecified)

package 'cvTools' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\tjoeun302-18\AppData\Local\Temp\RtmpSgkAzG\downloaded_packages

In [24]:
set.seed(123)
library(cvTools)
#n 샘플수, K교차검증횟수, type='random' 샘플선택을 랜덤으로
#cross<-cvFolds(n=10, K=5, type='random')
# consecutive 샘플선택을 순서대로
cross<-cvFolds(n=10, K=5, type='consecutive')
#$ interleaved 샘플 선택을 교대로
#cross<-cvFolds(n=10, K=5, type='interleaved')
cross

5-fold CV:
Fold   Index
   1       1
   1       2
   2       3
   2       4
   3       5
   3       6
   4       7
   4       8
   5       9
   5      10

In [25]:
# which 몇번째 분할, subset 인덱스값
cross$subsets[cross$which==1,1] #k=1일 때
cross$subsets[cross$which==2,1] #k=2일 때
cross$subsets[cross$which==3,1] #k=3일 때
cross$subsets[cross$which==4,1] #k=4일 때
cross$subsets[cross$which==5,1] #k=5일 때

[1] 1 2

[1] 3 4

[1] 5 6

[1] 7 8

[1]  9 10

In [27]:
for (k in 1:5){
    idx<-cross$subsets[cross$which==k, 1]
    cat('\nk=',k,'학습용\n')
    print(df[-idx,])
    cat('\nk=',k,'검증용\n')
    print(df[idx,])
}

k= 1 학습용
     Name Score
3  홍상수    70
4  이찬수    85
5  송희연    60
6  최승희    66
7  박만수    77
8  민지영    88
9  정선호    99
10 한상후   100

k= 1 검증용
    Name Score
1 김철수    90
2 이미영    85

k= 2 학습용
     Name Score
1  김철수    90
2  이미영    85
5  송희연    60
6  최승희    66
7  박만수    77
8  민지영    88
9  정선호    99
10 한상후   100

k= 2 검증용
    Name Score
3 홍상수    70
4 이찬수    85

k= 3 학습용
     Name Score
1  김철수    90
2  이미영    85
3  홍상수    70
4  이찬수    85
7  박만수    77
8  민지영    88
9  정선호    99
10 한상후   100

k= 3 검증용
    Name Score
5 송희연    60
6 최승희    66

k= 4 학습용
     Name Score
1  김철수    90
2  이미영    85
3  홍상수    70
4  이찬수    85
5  송희연    60
6  최승희    66
9  정선호    99
10 한상후   100

k= 4 검증용
    Name Score
7 박만수    77
8 민지영    88

k= 5 학습용
    Name Score
1 김철수    90
2 이미영    85
3 홍상수    70
4 이찬수    85
5 송희연    60
6 최승희    66
7 박만수    77
8 민지영    88

k= 5 검증용
     Name Score
9  정선호    99
10 한상후   100

In [28]:
set.seed(123) #랜덤 시드 고정
dim(iris) #데이터의 차원
# nrow() 행의 수
# sample(A,B) A에서 B를 샘플링
idx<-sample(1:nrow(iris), nrow(iris)*0.8)
tr<-iris[idx,] #학습용
te<-iris[-idx,] #검증용

dim(tr)
dim(te)
head(tr)
head(te)

[1] 150   5

[1] 120   5

[1] 30  5

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
14  4.3          3.0         1.1          0.1         setosa
50  5.0          3.3         1.4          0.2         setosa
118 7.7          3.8         6.7          2.2         virginica
43  4.4          3.2         1.3          0.2         setosa
150 5.9          3.0         5.1          1.8         virginica
148 6.5          3.0         5.2          2.0         virginica

   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  5.1          3.5         1.4          0.2         setosa
2  4.9          3.0         1.4          0.2         setosa
3  4.7          3.2         1.3          0.2         setosa
11 5.4          3.7         1.5          0.2         setosa
18 5.1          3.5         1.4          0.3         setosa
19 5.7          3.8         1.7          0.3         setosa

In [30]:
set.seed(123)
library(e1071)
library(caret)
# method-'cv' 교차검증법, number=5 5회 반복
trControl<-trainControl(method='cv',number=5)
# knn 알고리즘으로 k의 값을 1~10가지 테스트하여 정확도를 측정
# 학습용 데이터셋으로 실험
fit<-train(Species ~. , method='knn',
          tuneGrid=expand.grid(k=1:10),
          trControl=trControl, metric='Accuracy', data=tr)
fit

Warning message in load(system.file("models", "models.RData", package = "caret")):
"strings not representable in native encoding will be translated to UTF-8"

k-Nearest Neighbors

120 samples
  4 predictor
  3 classes: 'setosa', 'versicolor', 'virginica'

No pre-processing
Resampling: Cross-Validated (5 fold)
Summary of sample sizes: 96, 96, 96, 96, 96
Resampling results across tuning parameters:

  k   Accuracy   Kappa
   1  0.9583333  0.9372327
   2  0.9583333  0.9372327
   3  0.9666667  0.9497327
   4  0.9583333  0.9368407
   5  0.9500000  0.9240755
   6  0.9333333  0.8990796
   7  0.9750000  0.9622368
   8  0.9750000  0.9622368
   9  0.9666667  0.9494716
  10  0.9583333  0.9368407

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 8.

In [32]:
set.seed(123)
# 검증을 데이터셋으로 실험
fit<-train(Species ~ ., method='knn',
           tuneGrid=expand.grid(k=1:10),
           trControl=trControl, metric='Accuracy',data=te)
fit

Warning message in load(system.file("models", "models.RData", package = "caret")):
"strings not representable in native encoding will be translated to UTF-8"

k-Nearest Neighbors

30 samples
 4 predictor
 3 classes: 'setosa', 'versicolor', 'virginica'

No pre-processing
Resampling: Cross-Validated (5 fold)
Summary of sample sizes: 24, 24, 24, 24, 24
Resampling results across tuning parameters:

  k   Accuracy   Kappa
   1  1.0000000  1.00
   2  1.0000000  1.00
   3  1.0000000  1.00
   4  1.0000000  1.00
   5  1.0000000  1.00
   6  1.0000000  1.00
   7  1.0000000  1.00
   8  0.9666667  0.94
   9  0.8333333  0.70
  10  0.8333333  0.70

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was k = 7.

In [37]:
set.seed(123)
library(class)
#품종별로 5등분
group1<-cut(seq(1,50),breaks=5,labels=F)
group2<-cut(seq(51,100),breaks=5,labels=F)
group3<-cut(seq(101,150),breaks=5,labels=F)

# group1
# group2
# group3

fold<-c(group1,group2,group3) #5-fold 데이터셋
#fold
acc<-c() #정확도를 저장할 벡터
for (i in 1:5){
    ds.tr<-iris[fold != i, 1:4] #학습용 데이터셋
    ds.te<-iris[fold == i, 1:4] #검증용 데이터셋
    cl.tr<-factor(iris[fold != i,5]) #학습용 라벨
    cl.te<-factor(iris[fold == i,5]) #검증용 라벨
    pred<- knn(ds.tr, ds.te, cl.tr, k=7) #knn 모형에서 예측한 값
    acc[i]<- round(mean(pred==cl.te)*100,1) #소수 1자리에서 반올림
}
acc #5-fold 정확도
mean(acc) #평균 정확도

  [1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4
 [38] 4 4 4 5 5 5 5 5 5 5 5 5 5 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3
 [75] 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 1 1 1 1 1 1 1 1 1 1 2
[112] 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5
[149] 5 5

[1]  96.7 100.0  96.7  96.7 100.0

[1] 98.02