In [1]:
import pandas as pd
df=pd.read_csv('d:/data/creditcard/creditcard.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [2]:
df.groupby('Class').mean() #Class 그룹별 평균값

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [3]:
df['Class'].value_counts() #0정상거래 284315, 1 사기거래 492

0    284315
1       492
Name: Class, dtype: int64

In [4]:
train_cols=df.columns[1:30]
X=df[train_cols] #독립변수
y=df['Class'] #종속변수

In [5]:
#언더샘플링
from imblearn.under_sampling import RandomUnderSampler
X_sample,y_sample=RandomUnderSampler(random_state=0).fit_sample(X,y)
X_samp=pd.DataFrame(data=X_sample,columns=train_cols)
y_samp=pd.DataFrame(data=y_sample,columns=['Class'])
df2=pd.concat([X_samp,y_samp],axis=1)

Using TensorFlow backend.

In [6]:
df2['Class'].value_counts() #샘플링 후의 분포 확인

1    492
0    492
Name: Class, dtype: int64

In [7]:
#샘플링 데이터셋에서 X,y 구분
X=X_samp[train_cols]
y=y_samp['Class']

In [8]:
import statsmodels.api as sm
model=sm.Logit(y,X) #로지스틱 회귀분석 모형
result=model.fit()
result.summary2()
#R-squared: 0.831 모형설명력 83.1%

Optimization terminated successfully.
         Current function value: 0.117412
         Iterations 22

<class 'statsmodels.iolib.summary2.Summary'>
"""
                          Results: Logit
==================================================================
Model:              Logit            Pseudo R-squared: 0.831
Dependent Variable: Class            AIC:              289.0667
Date:               2020-02-19 10:57 BIC:              430.9238
No. Observations:   984              Log-Likelihood:   -115.53
Df Model:           28               LL-Null:          -682.06
Df Residuals:       955              LLR p-value:      9.3237e-221
Converged:          1.0000           Scale:            1.0000
No. Iterations:     22.0000
-------------------------------------------------------------------
            Coef.    Std.Err.     z     P>|z|     [0.025    0.975]
-------------------------------------------------------------------
V1         -17.6533    2.8759  -6.1383  0.0000   -23.2900  -12.0166
V2          23.0516    4.6354   4.9730  0.0000    13.9664   32.1367
V3         -44.1401    7.6704  -5.7546  0.0000   -59.1739  -29.1064
V4          28.2162    4.8258   5.8470  0.0000    18.7579   37.6745
V5         -28.7979    4.7999  -5.9997  0.0000   -38.2056  -19.3903
V6         -12.7996    2.3947  -5.3450  0.0000   -17.4931   -8.1061
V7         -63.3386   11.7109  -5.4085  0.0000   -86.2916  -40.3856
V8          12.6192    2.4920   5.0638  0.0000     7.7349   17.5035
V9         -30.2775    5.3746  -5.6335  0.0000   -40.8115  -19.7435
V10        -70.9719   12.5000  -5.6777  0.0000   -95.4715  -46.4724
V11         50.1646    8.9834   5.5842  0.0000    32.5575   67.7716
V12        -90.0617   16.0953  -5.5955  0.0000  -121.6080  -58.5155
V13          0.4736    0.1993   2.3756  0.0175     0.0829    0.8643
V14        -94.4417   16.8490  -5.6052  0.0000  -127.4651  -61.4182
V15         -2.1009    0.4038  -5.2026  0.0000    -2.8924   -1.3094
V16        -84.6566   15.1583  -5.5848  0.0000  -114.3664  -54.9468
V17       -152.9058   27.3912  -5.5823  0.0000  -206.5916  -99.2201
V18        -56.9486   10.2461  -5.5581  0.0000   -77.0306  -36.8666
V19         19.1888    3.5392   5.4219  0.0000    12.2522   26.1254
V20          7.1213    1.0501   6.7815  0.0000     5.0631    9.1794
V21         10.8542    1.9288   5.6273  0.0000     7.0738   14.6346
V22          2.3189    0.5296   4.3783  0.0000     1.2808    3.3570
V23          1.8149    0.9065   2.0021  0.0453     0.0382    3.5915
V24         -1.2647    0.4528  -2.7930  0.0052    -2.1522   -0.3772
V25          4.5660    1.0886   4.1942  0.0000     2.4323    6.6996
V26          1.5069    0.5089   2.9611  0.0031     0.5095    2.5043
V27         14.7519    2.5030   5.8937  0.0000     9.8461   19.6577
V28         14.0468    3.2494   4.3229  0.0000     7.6781   20.4155
Amount       0.0373    0.0120   3.1123  0.0019     0.0138    0.0608
==================================================================

"""

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#학습용 검증용 8:2로 구분
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)
model=LogisticRegression()
model.fit(X_train,y_train)

C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.9491740787801779
0.9289340101522843

In [11]:
from sklearn.metrics import confusion_matrix
pred=model.predict(X_test) #모형이 예측한 값
cm=confusion_matrix(y_test,pred) #실제값과 예측값 비교(오분류표)
cm

array([[88,  3],
       [11, 95]], dtype=int64)

In [12]:
#데이터프레임으로 변환
df_cm=pd.DataFrame(cm,index=['정상','사기'],columns=['정상','사기'])
df_cm

    정상  사기
정상  88   3
사기  11  95